# Generated by Django 2.2.4 on 2019-08-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('nucleotide_change', models.TextField(blank=True, null=True)),
                ('protein_change', models.CharField(blank=True, max_length=50, null=True)),
                ('other_mappings', models.TextField(blank=True, null=True)),
                ('other_name', models.TextField(blank=True, null=True)),
                ('transcripts', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('reported_classification', models.TextField(blank=True, null=True)),
                ('inferred_classification', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('last_evaluated', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('submitter_comment', models.TextField(blank=True, null=True)),
                ('assembly', models.TextField(blank=True, null=True)),
                ('chr', models.TextField(blank=True, null=True)),
                ('genomic_start', models.IntegerField(blank=True, null=True)),
                ('genomic_stop', models.IntegerField(blank=True, null=True)),
                ('ref', models.TextField(blank=True, null=True)),
                ('alt', models.TextField(blank=True, null=True)),
                ('accession', models.TextField(blank=True, null=True)),
                ('reported_ref', models.TextField(blank=True, null=True)),
                ('reported_alt', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
