# Generated by Django 2.2.4 on 2019-08-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene_lookup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='genomic_start',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='genomic_stop',
            field=models.TextField(blank=True, null=True),
        ),
    ]
